version: "3"
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: swordfish
      MYSQL_DATABASE: mysms
    ports:
      - "3306:3306"

  rails: &rails
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/mySMS
      - /mySMS/node_modules
    environment:
      DB_HOST: db
      DB_PWD: example
      DB_USER_NAME: root
      DB_PORT: 3306
    ports:
      - "3000:3000"
    depends_on:
      - db

  rails_test:
    <<: *rails
    # working_dir: /mySMS/my-sms
    # command: /bin/sh -c "cd ./mySMS/my-sms && bundle exec rails server"
    environment:
      DB_HOST: db
      DB_PWD: example
      DB_USER_NAME: root
      DB_PORT: 3306
      RAILS_ENV: test
      CYPRESS: 1
    ports:
      - "5002:3000"
